### ISSUE TITLE
Can't get message translations in non-template code

### ISSUE THREAD

**Issue by thadd** [yahoo/ember-intl#107]
I can't seem to figure out how to use translations in my route code. I didn't see anything in the README on how to do it properly so I dug through the code and as nearly as I can tell, I should be using the `findTranslation` method.

Here's my route code:

```javascript
export default Ember.Route.extend({
  auth: Ember.inject.service(),
  intl: Ember.inject.service(),

  beforeModel: function(transition) {
    if (this.get('auth').get('isAuthenticated')) {
      this._super(transition);
    } else {
      this.get('intl').findTranslation('messages.please_log_in').then(function(result) {
        // result should have my translated text
      });
    }
});
```

I'm able to use that key just fine in my templates via `{{format-message intl-get('messages.please_log_in')}}`, but when I try in the route (have also tried in controllers and components), I get the following failed assertion:

```
Assertion Failed: findTranslation should return an object of instance `IntlGetResult`
```

I've tried with both 1.3.0 and the current master but I get the same result. Am I missing something about how to get translations in my non-template code? Are the code examples around on the proper way to do it?

Also, is there a synchronous way to do it? It feels clunky to have to use a promise to pull the translations.

**Comment by jasonmit** [comment]
> Assertion Failed: findTranslation should return an object of instance `IntlGetResult`

Are you able to send me an example of you reproducing this?  What I am guessing is there is no translation for that key on the active locale (`this.get('intl.current');`).  I will look to improve the error/warning language there to prevent this confusion.

What `findTranslation` is doing is the following (in <2.0):
* Takes two args, one the message key and the other an optional locale.  Here you do not provide one so it uses whatever the `current` computed property is of the intl service.
* `this.container.lookup('locale:' + currentLocale);` will return the translation file it then simply does an Ember.get on the object the container lookup returns with that path, `messages.please_log_in`.
* If nothing is found, that error is thrown

If you give me access to the app that's having the issue, I'd be happy to look at what the cause is.

> Also, is there a synchronous way to do it?

That will be the default behavior in 2.0 on a branch right now.

**Comment by thadd** [comment]
Wow, I feel stupid. I must have spent an hour yesterday working on this and could never make it work, but now that I stripped things down it's working exactly as expected. I must have had a typo in my key or something.

Sorry for wasting your time and thanks for a great add-on!

**Comment by jasonmit** [comment]
I think ember-intl should do a better job at warning on typos and not found keys.  I'll make sure to address this in 2.0 as well.
