### ISSUE TITLE
update installation

### ISSUE THREAD

**Issue by caridy** [yahoo/ember-intl#126]
@jasonmit in the installation steps, the reference to the polyfill should be updated. using `<script src="/assets/intl/polyfill/Intl.complete.js"></script>` is almost imposible since it is too big. Instead, we shoudl include the Intl.min.js and the corresponding locale data.

In the near future, we can reference to the FT polyfill service, as a way to optimize the polyfill inclusion.

**Comment by caridy** [comment]
Once https://github.com/Financial-Times/polyfill-service/pull/410 clears, we can update the docs to point to the optimized url provided by that service.

**Comment by caridy** [comment]
to be clear, complete.js is only meant to be used on the server side thru npm.

**Comment by jasonmit** [comment]
The issue is how do we load the corresponding locale data.  We need to basically load the shim and then register locale data once the polyfill is evaluated.  I had some ideas but have since removed all that logic and was waiting until "Fastboot" to pass down the locale data from the server to the client that are needed

**Comment by caridy** [comment]
yeah, I'm ok waiting for the FT polyfill service, in which case we can just rely on that one since the polyfill and the locale data are just runtime patches, and has no ties to ember-intl.
