### ISSUE TITLE
Injecting `this.get('intl')` in acceptance tests

### ISSUE THREAD

**Issue by ryrych** [yahoo/ember-intl#252]
How can I use it in acceptance tests? The setup from https://github.com/yahoo/ember-intl/wiki/Testing---Integration doesn't work as `this` scope is not scoped to component.

**Comment by elwayman02** [comment]
@ryrych if you're in an acceptance test, the entire app should be spun up, and the `intl` service should be available wherever it is used. Why do you need to access the service within the actual test code?

**Comment by jasonmit** [comment]
@ryrych in order to achieve this, you'll need to use a private API.

Your acceptance tests are likely calling the test helper `startApp`, which returns an instance of `Ember.Application`.  You can pick the service off the instance via `var intl = application.__container__.lookup('service:intl');`.

In the future, you will not have to go through this, as the tests suite will some how expose an instance of `Ember.ApplicationInstance` instead of `Ember.Application`.  Once that happens, you'll lookup the service via `application.lookup('service:intl');`

Related: https://github.com/emberjs/ember.js/issues/12277
