### ISSUE TITLE
Acceptance tests failing with format-helpers

### ISSUE THREAD

**Issue by enspandi** [yahoo/ember-intl#269]
Getting `ReferenceError: Can't find variable: Intl` in acceptance tests when using a format helper:
`{{format-date (get attribute 'value')}}`

But the translation helper works without problems:
`{{t 'attributes.date'}}`

So Intl is available in case of t-helper but not format-date-helper?

Using version 2.0.0-rc.5 and PhantomJS 1.9.

**Comment by jasonmit** [comment]
PhantomJS in one of the browsers which doesn't implement the Intl API.  The financial times polyfill will also not work in this case since they do not target phantomjs.

Adding the script tag that's included in your assets folder, for free, is documented here:
https://github.com/yahoo/ember-intl#writing-unit-tests
