### ISSUE TITLE
Consider message as default key

### ISSUE THREAD

**Issue by bakura10** [yahoo/ember-intl#46]
Hi,

When formatting message, we are forced to specify the full path: {{format-message (intl-get 'messages.foo.bar')}}.

Can't this actually always assume that messages is the root, so that it allows us to simply refer to message using "foo.bar" instead of "messages.foo.bar" ? :)

**Comment by jasonmit** [comment]
This is already possible today.  See my last set of comments in https://github.com/yahoo/ember-intl/issues/23

**Comment by jasonmit** [comment]
Update since I was on my phone and just want to make one point clear:
```js
import Locale from 'ember-intl/models/locale';

// app/locales/en.js
export default Locale.extend({
  // optional, but the default
  foo: 'bar'
});
```

`{{format-message (intl-get 'foo')}}` outputs `bar`

If this is the path you plan on taking, I suggest creating your own locales class which extends from `ember-intl/models/locales` where you implement your own addMessage/addMessages (if you plan to use them).  

See: https://github.com/yahoo/ember-intl/blob/master/addon/models/locale.js#L12-L29

If you have no plans to sideload messages, then you can ignore changing them.
