### ISSUE TITLE
Support for runtime-loaded CLDR

### ISSUE THREAD

**Issue by gigafied** [yahoo/ember-intl#69]
My current project is using AMD w/ Ember. Thus during dev, we have no build step. Without the ability to load the CLDR data on-demand, I am unable to implement `ember-intl`.

Apart from my specific issue though, it would be good to have an option to create Locales and register them as needed during runtime. Say our backend were to have language management, with the ability to add new languages or remove languages. Currently this isn't possible as the full list of languages needs to be included when building the JS.

**Comment by jasonmit** [comment]
@gigafied when you say locales are you referring to the CLDR, translations, or both?

**Comment by gigafied** [comment]
Both.

**Comment by jasonmit** [comment]
@gigafied I have changes to resolve portions of your requirements in #68.

However, The CLDR extraction logic hasn't been solved yet.  But I think the path will be to expose the new broccoli plugin (https://github.com/yahoo/ember-intl/pull/68/files#diff-616282132dc0285e5107b705ebf796eaR1) as a third party module where you can use to push locale to your asset tree instead of your app tree.

**Comment by jasonmit** [comment]
https://github.com/yahoo/ember-intl/issues/41 I'm going to use this issue as the reference for this feature since this is a duplicate.
